### PR TITLE
Gwenchee edits

### PR DESCRIPTION
**Pull request by jbae11**
This PR modifies the `commodity_dict` so that we don't need 4 variables to pass along. `pref_dict`, `second_driving_commod` and all those variables are put into `commodity_dict`. 
Also updates tests to reflect that

### CODE REVIEW

**Comment by jbae11** [comment]
@pep8speaks pep8ify

**Comment by gwenchee** [comment]
You changed alot of things, so it's really hard to check if any functionality got affected, so i think we need tests for each function before we merge it

**Comment by gwenchee** [comment]
@jbae11 Also, can this be a separate PR from the https://github.com/ergs/d3ploy/pull/157 since its a clean up of the code?

**Comment by jbae11** [comment]
there are tests for the changed `solver` function. And the ci checks if the d3ploy works

**Pull request merged**
